# Generated by Django 4.1.4 on 2022-12-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
