# Generated by Django 4.1.4 on 2022-12-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(default=1, upload_to='photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
